--- #YAML:1.0
name:                Object-Exercise
version:             1.13
abstract:            Generic execution & benchmark harness for method calls.
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Benchmark:                     1.07
    File::Basename:                0
    IO::Handle:                    0
    Scalar::Util:                  0
    strict:                        0
    Symbol:                        0
    Test::Deep:                    0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
