--- #YAML:1.0
name:               Object-Exercise
version:            1.14
abstract:           Generic execution & benchmark harness for method calls.
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Benchmark:       1.07
    File::Basename:  0
    IO::Handle:      0
    Scalar::Util:    0
    strict:          0
    Symbol:          0
    Test::Deep:      0
    Test::More:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
